### ISSUE TITLE
docusign/esign-client v 3 new API classes

### ISSUE THREAD

**Issue by astridblahblahblah** [Tucker-Eric/docusign-rest-client#1]
Hi Eric,

I was just wondering if you were planning on updating the wrapper to use docusign/esign-client version ^3.0? There is a very useful update for signing groups and I can't just manually override the php rest client version because of the constraint. I'm not sure how I should go about this though so if you need me to create a pull request adding the empty API classes and you can create a new version of the wrapper just let me know.

Thanks,
Astrid

**Comment by Tucker-Eric** [comment]
I haven't had a chance to look through the new changes in depth yet.  Do know if 3.0 is backwards compatible? It looks like authentication changed which may cause some breaking changes.  If you wanna create a pull request to update the changes I'd have no problem creating another branch for 3.0 if it's not backwards compatible or merging if it is.

**Comment by astridblahblahblah** [comment]
Thanks, I've started work on it, not much of a change so I should be able to send a pull request soon.
