### ISSUE TITLE
PHP 8 is unsupported

### ISSUE THREAD

**Issue by Jmille65** [Tucker-Eric/docusign-rest-client#10]
Thanks for this package- are there plans to support PHP 8?

**Comment by Tucker-Eric** [comment]
As far as I can tell I don't believe PHP 8 introduced any BC breaks that would affect this package so it should be as easy as updating the composer.json. 

Will test with php8 just to be sure though.

**Comment by Tucker-Eric** [comment]
[4.0.0](https://github.com/Tucker-Eric/docusign-rest-client/releases/tag/4.0.0) Tested with PHP 7.3 & PHP 8
