### ISSUE TITLE
I got the error on composer update: tucker-eric/docusign-rest-client[2.0.0, 3.0.0] require php ^7.2 -> your php version (8.0.2) does not satisfy that requirement.

### ISSUE THREAD

**Issue by prempmalviya** [Tucker-Eric/docusign-rest-client#11]
Hello Mr.Tucker,
I am upgrading my laravel version from 6 to 8. For this also upgrade my php version from 7.2 to 8.0.
I am also change in composer.json as tucker-eric/laravel-docusign": "^3.0.0. But when i run composer update,
i got the error:

 Problem 1
    - tucker-eric/laravel-docusign[3.0.0, ..., 3.1.0] require tucker-eric/docusign-rest-client ~2.0|~3.0 -> satisfiable by tucker-eric/docusign-rest-client[2.0.0, 3.0.0].
    - tucker-eric/docusign-rest-client[2.0.0, 3.0.0] require php ^7.2 -> your php version (8.0.2) does not satisfy that requirement.
    - Root composer.json requires tucker-eric/laravel-docusign ^3.0.0 -> satisfiable by tucker-eric/laravel-docusign[3.0.0, 3.1.0].

Thankyou so much in Advance.

**Comment by Tucker-Eric** [comment]
Use [4.0.0](https://github.com/Tucker-Eric/docusign-rest-client/releases/tag/4.0.0), it supports php8

**Comment by prempmalviya** [comment]
Dear Mr. Tucker,

Thanks for the Reply.
I got error when i used 4.0.0

 Problem 1
    - tucker-eric/laravel-docusign[4.0.0, ..., 4.1.0] require tucker-eric/docusign-rest-client ~2.0|~3.0 -> satisfiable by tucker-eric/docusign-rest-client[2.0.0, 3.0.0].
    - tucker-eric/docusign-rest-client[2.0.0, 3.0.0] require php ^7.2 -> your php version (8.0.2) does not satisfy that requirement.
    - Root composer.json requires tucker-eric/laravel-docusign ^4.0.0 -> satisfiable by tucker-eric/laravel-docusign[4.0.0, 4.0.1, 4.1.0]

Thanks
