### ISSUE TITLE
Dear Mr. Tucker,

### ISSUE THREAD

**Issue by prempmalviya** [Tucker-Eric/docusign-rest-client#12]
Dear Mr. Tucker,

Thanks for the Reply.
I got error when i used 4.0.0

 Problem 1
    - tucker-eric/laravel-docusign[4.0.0, ..., 4.1.0] require tucker-eric/docusign-rest-client ~2.0|~3.0 -> satisfiable by tucker-eric/docusign-rest-client[2.0.0, 3.0.0].
    - tucker-eric/docusign-rest-client[2.0.0, 3.0.0] require php ^7.2 -> your php version (8.0.2) does not satisfy that requirement.
    - Root composer.json requires tucker-eric/laravel-docusign ^4.0.0 -> satisfiable by tucker-eric/laravel-docusign[4.0.0, 4.0.1, 4.1.0]

Thanks

_Originally posted by @lovelight24 in https://github.com/Tucker-Eric/docusign-rest-client/issues/11#issuecomment-790291676_

**Comment by Tucker-Eric** [comment]
Use [4.1.0](https://github.com/Tucker-Eric/Laravel-Docusign/releases/tag/4.1.0) of Laravel-Docusign

**Comment by prempmalviya** [comment]
Issue not resolved.

tucker-eric/laravel-docusign 4.1.0 requires tucker-eric/docusign-rest-client ~2.0|~3.0
tucker-eric/docusign-rest-client[2.0.0, 3.0.0] require php ^7.2 -> your php version (8.0.2) does not satisfy that requirement.

**Comment by Tucker-Eric** [comment]
Ahhh, I see now. Sorry about that. Use [4.1.1](https://github.com/Tucker-Eric/Laravel-Docusign/releases/tag/4.1.1) of Laravel-Docusign. I just updated that to support ~4.0 of docusign-rest-client.

**Comment by prempmalviya** [comment]
Thanks Mr. Tucker.
