### ISSUE TITLE
prefillTabs missing

### ISSUE THREAD

**Issue by pcottrell** [Tucker-Eric/docusign-rest-client#14]
The latest version of the PHP SDK for DocuSign supports prefill tabs.

-- https://github.com/docusign/docusign-esign-php-client/blob/master/src/Model/TemplateTabs.php

Any plans to support the updated library?

**Comment by Tucker-Eric** [comment]
This should be supportable. We'd just need to update to 6.X of docusign-esign-php-client

**Comment by FrankWiebe** [comment]
Any updates on this? Looking to use PrefillTabs

**Comment by Tucker-Eric** [comment]
Included in [5.0.0](https://github.com/Tucker-Eric/docusign-rest-client/releases/tag/5.0.0)

**Comment by FrankWiebe** [comment]
Will the Laravel wrapper package be upgraded as well to support this new version?

**Comment by Tucker-Eric** [comment]
@FrankWiebe just published [6.0.0](https://github.com/Tucker-Eric/Laravel-Docusign/releases/tag/6.0.0) of that package.

**Comment by FrankWiebe** [comment]
Thanks @Tucker-Eric
