### ISSUE TITLE
Deprecation of Legacy Authentication on September

### ISSUE THREAD

**Issue by Theo4** [Tucker-Eric/docusign-rest-client#15]
Hello Eric,

I've been following and learning a lot via this repo
Did you plan to upgrade this wrapper to the new OAuth 2 version of Docusign?

Have a nice day,

**Comment by Tucker-Eric** [comment]
I'd like to but finding the bandwidth to do so is difficult right now.  I'm definitely open to a pull request for it.

**Comment by wehostadm** [comment]
HI @Tucker-Eric 

Should be nice to update the bundle to the new OAuth 2 authentication.
Otherwise, if you don't have time to do it, is it another bundle for that ? 

Thanks

**Comment by Tucker-Eric** [comment]
@wehostadm not that I know of but still open to a pr for this
