### ISSUE TITLE
Example in Readme seems to be wrong

### ISSUE THREAD

**Issue by wehostadm** [Tucker-Eric/docusign-rest-client#18]
Hi,

I think the example is wrong : 
```
$client = new DocuSign\Rest\Client([
	'impersonated_user_id' => $impersonated_user_id,
	'integrator_key'       => $integrator_key,
	'host'                 => $host,
	'private_key'          => $private_key,
	'auth_server'          => $auth_server
]);

```
Indeed, the class Client does not handle impersonated_user_id, private_key and auth_server parameters.

What is wrong ? 

Thanks,

**Comment by Tucker-Eric** [comment]
@wehostadm I'm open to a PR for this if you're willing to open one?

**Comment by wehostadm** [comment]
@Tucker-Eric Seems to be good, I saw a PR for this and the documentation has been updated :)

Thanks
