### ISSUE TITLE
Need to downgrade to 2.0.0 version with php 8.1

### ISSUE THREAD

**Issue by wehostadm** [Tucker-Eric/docusign-rest-client#19]
Hi,

Using a version >= 3.0.0, the authentication with the old method (user + password) does not work anymore.

Everything is working fine in the 2.0.0 version but this version is locked to PHP 7.4 version.

Can you allow the PHP 8.1 version with the version 2.0.0 of this bundle ? 

Thanks,

**Comment by Tucker-Eric** [comment]
Ya, I'm open to a pr for this

**Comment by wehostadm** [comment]
It is ok now ;)

Thanks a lot :)
