### ISSUE TITLE
New authentification OAuth2 : can you release a new version of this bundle ?

### ISSUE THREAD

**Issue by wehostadm** [Tucker-Eric/docusign-rest-client#20]
Hi @Tucker-Eric 

I saw a PR for the new OAuth2 authentification but in my composer.json, I do not see an update for your bundle.

Can you release a new version ? In order to have your nice new feature and try it before September where the old authentification based on username + password will be disabled.

Thanks,

**Comment by Tucker-Eric** [comment]
release created as [6.0.0](https://github.com/Tucker-Eric/docusign-rest-client/releases/tag/6.0.0)
