### ISSUE TITLE
Usage question 

### ISSUE THREAD

**Issue by blorange2** [Tucker-Eric/docusign-rest-client#4]
If I want to access a nested API function with a base level API endpoint such as Accounts, how would I achieve this?

I'm trying to make a call to the following endpoint:

`GET /v2/accounts/{accountId}/templates/{templateId}/recipients/{recipientId}/tabs`

In the README it says the methods on the model accept an array of parameters, does this mean I would have to do the following?

$client->accounts->templates({
'template_id' => '',
'recipient_id' => ''
})

I'm trying to pre-fill a document's custom fields, but having read through the API I can't see a way to map pre-existing fields to data, only define and populate new fields.

Is what I'm thinking actually even possible?

**Comment by Tucker-Eric** [comment]
Looking at the source it looks like the first account returned in the login response is the account used for future calls after that and is automatically prepended to the argument list.

Since this is a thin wrapper around the docusign-php-client we'd actually be using the [`listTabs`](https://github.com/docusign/docusign-php-client/blob/master/src/Api/TemplatesApi.php#L5772) method on the `TemplatesApi` class.

So for this one it looks like it should be:
```php
$client->templates->listTabs($recipient_id, $template_id);
```

**Comment by blorange2** [comment]
> Looking at the source it looks like the first account returned in the login response is the account used for future calls after that and is automatically prepended to the argument list.
> 
> Since this is a thin wrapper around the docusign-php-client we'd actually be using the [`listTabs`](https://github.com/docusign/docusign-php-client/blob/master/src/Api/TemplatesApi.php#L5772) method on the `TemplatesApi` class.
> 
> So for this one it looks like it should be:
> 
> ```
> $client->templates->listTabs($recipient_id, $template_id);
> ```

Just because I'm sometimes a bit dense. Do you just look for the equivalent from the PHP wrapper?

**Comment by Tucker-Eric** [comment]
Yup.

This client wraps that and will take care of injecting the account id as the first parameter to all methods that require it.

**Comment by blorange2** [comment]
That's very cool. I think I'll close this and go find out how to grab the recipient ID, basically a guy made a template and added a load of tabs to it that he wants me to pre-fill via a webform, but I've not even been given any labels, so it's been 'interesting'.

This wrapper has been super helpful though

**Comment by blorange2** [comment]
@Tucker-Eric just to follow up, I didn't see a tabs api so in this case are they passed per signer?

**Comment by Tucker-Eric** [comment]
@blorange2 the way I would approach it based on the uri `/v2/accounts/{accountId}/templates/{templateId}/recipients/{recipientId}/tabs`. Anything that is account level is automatically handled post authentication for you so we can omit the `/v2/accounts/{accountId}` portion, which leaves us `templates/{templateId}/recipients/{recipientId}/tabs`. With `templates` as the first uri segment, that led me to [`TemplatesApi`](https://github.com/docusign/docusign-php-client/blob/master/src/Api/TemplatesApi.php) which is where I found the `listTabs` method that is per recipient which seemed like it fit your use case.

Looking at [`Docusign's TemplatesApi`](https://github.com/docusign/docusign-php-client/blob/master/src/Api/TemplatesApi.php) it looks like there is a [`listDocuments`](https://github.com/docusign/docusign-php-client/blob/master/src/Api/TemplatesApi.php#L5535) method that can respond with all tabs when passed the option to like:

```php
$templateApi = $client->templates;
$templateApi->listDocuments($template_id, $templateApi->listDocumentsOptions(['include_tabs' => true]));
```

I hope this makes some sense?

**Comment by blorange2** [comment]
That makes a whole lot of sense. It's a valuable lesson in terms of knowing what packages are making easier in terms of interaction.

I'll give this a go, thanks again.
