### ISSUE TITLE
Update SDK to 5.1

### ISSUE THREAD

**Issue by jdombroski** [Tucker-Eric/docusign-rest-client#5]
Can we get an update to `docusign/esign-client` ^5.1? There are several bug fixes I need in my application (see [this serializer issue](https://github.com/docusign/docusign-php-client/issues/60))

**Comment by Tucker-Eric** [comment]
Yup! Should have something out shortly!

**Comment by Tucker-Eric** [comment]
Added in [3.0.0](https://github.com/Tucker-Eric/docusign-rest-client/releases/tag/3.0.0)
