### ISSUE TITLE
I got the error on installing Tucker-Eric / docusign-rest-client.

### ISSUE THREAD

**Issue by kzwkyawzinwai** [Tucker-Eric/docusign-rest-client#7]
Hello [Mr.Eric Tucker](https://github.com/Tucker-Eric)

I cannot install the latest version (v3.0) of "[docusign-rest-client](https://github.com/Tucker-Eric/docusign-rest-client)" because of the below error. Now I've to downgrade to version ^2.0 and use it. I think you need to upgrade in that [Tucker-Eric/Laravel-Docusign](https://github.com/Tucker-Eric/Laravel-Docusign) too.

> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - tucker-eric/laravel-docusign 2.2.0 requires tucker-eric/docusign-rest-client ^2.0 -> satisfiable by tucker-eric/docusign-rest-client[2.0.0] but these conflict with your requirements or minimum-stability.
>     - tucker-eric/laravel-docusign 2.2.0 requires tucker-eric/docusign-rest-client ^2.0 -> satisfiable by tucker-eric/docusign-rest-client[2.0.0] but these conflict with your requirements or minimum-stability.
>     - Installation request for tucker-eric/laravel-docusign ^2.2 -> satisfiable by tucker-eric/laravel-docusign[2.2.0].

 Thanks for creating such a great work.

**Comment by Tucker-Eric** [comment]
Whoops! Yes, you are correct. Will get update out shortly!

**Comment by Tucker-Eric** [comment]
This has been updated in [Laravel-Docusign 3.0.0](https://github.com/Tucker-Eric/Laravel-Docusign/releases/tag/3.0.0)
