### ISSUE TITLE
Question, help needed

### ISSUE THREAD

**Issue by evanlegamer** [Tucker-Eric/docusign-rest-client#8]
Hi, your php wrapper of DocuSign looks really great, I just have a little question,
do this wrapper support authentication through JWT ? 

In my use case, I need to make every operation on DocuSign with a single account, and so, for a document I need to specify who is the issuer and the signatory. Is this possible with your Wrapper ?

Thank you in advance for your help.

**Comment by Tucker-Eric** [comment]
It currently does not. It only supports the `X-DocuSign-Authentication` header auth method for the account the header credentials is making requests against.
