### ISSUE TITLE
getRecipientViewRequest Seems to not being implemented

### ISSUE THREAD

**Issue by evanlegamer** [Tucker-Eric/docusign-rest-client#9]
Hi guys, i did not find the getRecipientView request in the repo.

This endpoint is useful to embed the signing process,  you can find this function here on docusign : https://github.com/docusign/code-examples-php/blob/master/src/EG001EmbeddedSigning.php

do you think you can add this ?

thank you in advance

**Comment by evanlegamer** [comment]
ok is it this ?

` * @method Models\RecipientViewRequest recipientViewRequest(array $props = ['assertion_id' => null, 'authentication_instant' => null, 'authentication_method' => null, 'client_user_id' => null, 'email' => null, 'ping_frequency' => null, 'ping_url' => null, 'recipient_id' => null, 'return_url' => null, 'security_domain' => null, 'user_id' => null, 'user_name' => null, 'x_frame_options' => null, 'x_frame_options_allow_from_url' => null])`

**Comment by evanlegamer** [comment]
in fact this is this one that i could not found in the the repo !

getRecipientView

**Comment by Tucker-Eric** [comment]
Looking at the source (https://github.com/docusign/code-examples-php/blob/22e49cbec2268d2e82533630a841183b238d3078/src/Services/SignatureClientService.php#L107-L123) it's just calling the envelopes api and creating an instance of `DocuSign\eSign\Model\RecipientViewRequest;` with some defaults.  (https://github.com/docusign/code-examples-php/blob/22e49cbec2268d2e82533630a841183b238d3078/src/Services/SignatureClientService.php#L88-L97) 

This is already supported:
- Create RecipientViewRequest - https://github.com/Tucker-Eric/docusign-rest-client/blob/3.0.0/src/Client.php#L378
- createRecipientView - https://github.com/Tucker-Eric/docusign-rest-client/blob/3.0.0/src/Api/Envelopes.php#L35

```php
$envelope_id = 'ENVELOPE_ID';

$client = new DocuSign\Rest\Client([
    'username'       => $username,
    'password'       => $password,
    'integrator_key' => $integrator_key,
    'host'           => $host
]);

$recipientViewRequest = $client->recipientViewRequest([
    'authentication_method' => 'none',
    'client_user_id'        => 1000,
    'recipient_id'          => '1',
    'return_url'            => '',
    'user_name'             => '',
    'email'                 => ''
]);

$results = $client->envelopes->createRecipientView($envelope_id, $recipientViewRequest)
```
